// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPfoq2zCUU-y6r4aKu_4HW1Fmwfhi2tN0',
    appId: '1:949361682359:web:d58c5a4c01fc507bb06a32',
    messagingSenderId: '949361682359',
    projectId: 'testktorysflutconf',
    authDomain: 'testktorysflutconf.firebaseapp.com',
    storageBucket: 'testktorysflutconf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0pus4ohE0g4UJb-y8qah2ydIz5GyLWoc',
    appId: '1:949361682359:android:e19c501eda7d4387b06a32',
    messagingSenderId: '949361682359',
    projectId: 'testktorysflutconf',
    storageBucket: 'testktorysflutconf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIZNLNQk2_3I564pz5e2cQCynC2FEusZo',
    appId: '1:949361682359:ios:d02f2163b874f22eb06a32',
    messagingSenderId: '949361682359',
    projectId: 'testktorysflutconf',
    storageBucket: 'testktorysflutconf.appspot.com',
    iosBundleId: 'com.example.praca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIZNLNQk2_3I564pz5e2cQCynC2FEusZo',
    appId: '1:949361682359:ios:d02f2163b874f22eb06a32',
    messagingSenderId: '949361682359',
    projectId: 'testktorysflutconf',
    storageBucket: 'testktorysflutconf.appspot.com',
    iosBundleId: 'com.example.praca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPfoq2zCUU-y6r4aKu_4HW1Fmwfhi2tN0',
    appId: '1:949361682359:web:c64597831b0e2b53b06a32',
    messagingSenderId: '949361682359',
    projectId: 'testktorysflutconf',
    authDomain: 'testktorysflutconf.firebaseapp.com',
    storageBucket: 'testktorysflutconf.appspot.com',
  );
}
